<!DOCTYPE html>
<html lang="pt"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Rafael Pucci">
  <meta name="dcterms.date" content="2026-08-27">
  <title>EAE1317 — Economia do Meio Ambiente e dos Recursos Naturais – Permissões Negociáveis e Subsídios</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <link rel="stylesheet" href="../_assets/styles.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Permissões Negociáveis e Subsídios</h1>
  <p class="subtitle">EAE1317 — Economia do Meio Ambiente e dos Recursos Naturais</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Rafael Pucci 
</div>
</div>
</div>

  <p class="date">2026-08-27</p>
</section>
<section id="aula-passada" class="slide level2">
<h2>Aula Passada</h2>
<ul>
<li>O leque de instrumentos de <span class="citation" data-cites="keohane2016">Keohane e Olmstead (<a href="#/referências" role="doc-biblioref" onclick="">2016</a>)</span></li>
<li>Comando e Controle
<ul>
<li>Requisito de performance e requisito de tecnologia</li>
<li>Limite único <span class="math inline">\(\bar{e}={E}^{*}/J\)</span> gera peso morto quando as firmas diferem</li>
</ul></li>
<li>Imposto sobre Emissões
<ul>
<li><span class="math inline">\({\tau }^{*}={D}^{′}\left({E}^{*}\right)\)</span> induz a alocação de Pareto</li>
<li>Firmas escolhem sozinhas quanto abater: <span class="math inline">\(-{C}_{j}^{′}\left({e}_{j}\right)=\tau\)</span></li>
</ul></li>
</ul>
</section>
<section id="agenda" class="slide level2">
<h2>Agenda</h2>
<ul>
<li>Permissões Negociáveis
<ul>
<li>Cotas negociáveis</li>
<li>Leilão de permissões</li>
<li>Distribuição de permissões transferíveis</li>
</ul></li>
<li>Subsídios ao Abatimento</li>
</ul>
<div class="no-bullet">
<p>Referências: Phaneuf e Requate, cap. 3; Keohane e Olmstead, cap. 8</p>
</div>
</section>
<section id="as-duas-categorias-de-hoje" class="slide level2">
<h2>As duas categorias de hoje</h2>
<div class="step-map">
<div class="step">
<p><strong>1. Prescrever</strong> o regulador diz o que fazer: tecnologia obrigatória ou limite de emissão por fonte</p>
</div>
<div class="step now">
<p><strong>2. Precificar</strong> o regulador põe um preço na emissão: imposto ou subsídio</p>
</div>
<div class="step now">
<p><strong>3. Limitar quantidade</strong> o regulador fixa o total e deixa o mercado repartir permissões</p>
</div>
<div class="step">
<p><strong>4. Informar</strong> o regulador informa população com inventários de emissão, selos e certificações</p>
</div>
</div>
<ul>
<li>Não tratamos ainda da caixa 3.</li>
<li>Falaremos da caixa 2 novamente, porque o <strong>subsídio</strong> é o outro lado da moeda do imposto.</li>
</ul>
</section>
<section id="permissões-negociáveis" class="slide level2 section-cover">
<h2>Permissões Negociáveis</h2>
</section>
<section id="comando-e-controle-com-cotas-negociáveis" class="slide level2">
<h2>Comando e Controle com Cotas Negociáveis</h2>
<ul>
<li>Suponha, alternativamente, que o limite seja global <span class="math inline">\(\rightarrow E={E}^{*}\)</span>.</li>
<li>Suponha, ainda, que cada firma tenha <strong>cotas de poluição idênticas e negociáveis</strong> fixadas em <span class="math inline">\(\bar{e}=\frac{{E}^{*}}{2}\)</span>.</li>
<li>Qual firma estaria disposta a comprar cotas? E vender?</li>
</ul>
<div class="no-bullet">
<p>A figura é a mesma da aula passada. Só a leitura muda.</p>
</div>
</section>
<section id="a-mesma-figura-outra-leitura" class="slide level2">
<h2>A mesma figura, outra leitura</h2>
<div class="diagram">
<p><img data-src="../_assets/figuras/06-padrao-3.svg" style="max-height:300px"></p>
</div>
<ul>
<li>Na aula passada, <span class="math inline">\(B\)</span> e <span class="math inline">\(C\)</span> eram uma realocação que o regulador <strong>não</strong> conseguia fazer, e o saldo <span class="math inline">\(B-C\)</span> era peso morto.</li>
<li><span class="fragment" data-fragment-index="1">Com direito de venda, essa realocação vira uma <strong>troca voluntária</strong>, e as duas firmas ganham.</span></li>
</ul>
</section>
<section id="comando-e-controle-com-cotas-negociáveis-1" class="slide level2">
<h2>Comando e Controle com Cotas Negociáveis</h2>
<ul>
<li>Quanto a Firma 1 estaria disposta a pagar para comprar cotas da Firma 2?
<ul>
<li><span class="fragment" data-fragment-index="1">Firma 1 pagaria no máximo <span class="math inline">\(B\)</span> por mais cotas.</span></li>
<li><span class="fragment" data-fragment-index="1">Firma 1 poderia aumentar emissões em <span class="math inline">\({e}_{1}^{*}-\bar{e}\)</span>.</span></li>
</ul></li>
<li><span class="fragment" data-fragment-index="1">Quanto a Firma 2 aceitaria receber pelas cotas?</span>
<ul>
<li><span class="fragment" data-fragment-index="2">Firma 2 aceitaria pelo menos <span class="math inline">\(C\)</span>.</span></li>
<li><span class="fragment" data-fragment-index="2">E teria que reduzir poluição em <span class="math inline">\(\bar{e}-{e}_{2}^{*}\)</span>.</span></li>
</ul></li>
<li><span class="fragment" data-fragment-index="2">Quando essa troca seria mutuamente benéfica?</span>
<ul>
<li><span class="fragment" data-fragment-index="3">Isto seria mutuamente benéfico se <span class="math inline">\(B&gt;C\)</span>.</span></li>
</ul></li>
</ul>
</section>
<section id="comando-e-controle-com-cotas-negociáveis-2" class="slide level2">
<h2>Comando e Controle com Cotas Negociáveis</h2>
<ul>
<li>Este exemplo ilustra o conceito de “ganhos de especialização”.
<ul>
<li>Análogo a questões de Economia Internacional (vantagens comparativas).</li>
</ul></li>
<li>Firmas mais eficientes em abatimento podem absorver emissões de firmas menos eficientes.
<ul>
<li>Se houver mecanismo de troca.</li>
</ul></li>
</ul>
<div class="no-bullet">
<p>Falta dizer como se forma o preço dessa troca. Trataremos disso a seguir.</p>
</div>
</section>
<section id="leilão-de-permissões" class="slide level2 section-cover">
<h2>Leilão de Permissões</h2>
</section>
<section id="leilão-de-permissões-1" class="slide level2">
<h2>Leilão de Permissões</h2>
<div class="no-bullet">
<p>Suponha que, ao invés de cobrar um imposto ex-post da firma poluidora, o governo leiloe permissões ex-ante.</p>
</div>
<ul>
<li>Neste caso, o governo oferta <span class="math inline">\(L\)</span> permissões.</li>
<li>O preço de equilíbrio do leilão é dado por <span class="math inline">\(\sigma\)</span>.</li>
</ul>
<div class="no-bullet">
<p>Qual função de custo total a firma minimiza neste caso?</p>
</div>
</section>
<section id="leilão-de-permissões-2" class="slide level2">
<h2>Leilão de Permissões</h2>
<ul>
<li>Novamente, teremos <span class="math inline">\(T{C}_{j}\left({e}_{j}\right)={C}_{j}\left({e}_{j}\right)+\sigma {e}_{j}\)</span></li>
<li>A C.P.O. será análoga ao caso do imposto: <span class="math inline">\(-{C}_{j}^{′}\left({e}_{j}\right)=\sigma\)</span></li>
<li>Qual será o preço que maximiza o bem-estar social?</li>
</ul>
<div class="eq-block">
<p><span class="math display">\[{\sigma }^{*}={D}^{′}\left({E}^{*}\right)\]</span></p>
</div>
<ul>
<li><span class="fragment" data-fragment-index="1">Para a firma, permissão leiloada e imposto são a mesma despesa por unidade emitida.</span></li>
</ul>
</section>
<section id="leilão-de-permissões-3" class="slide level2">
<h2>Leilão de Permissões</h2>
<ul>
<li>Também podemos pensar na demanda por emissões em função do preço das permissões.</li>
<li>Assim, teremos uma função de demanda agregada por emissões igual a</li>
</ul>
<div class="eq-block">
<p><span class="math display">\[E\left(\sigma \right)=\sum_{j=1}^{J} {e}_{j}(\sigma )\]</span></p>
</div>
<div class="no-bullet">
<p>É a mesma soma horizontal que já vimos, porém com <span class="math inline">\(\sigma\)</span> no lugar de <span class="math inline">\(\tau\)</span>.</p>
</div>
</section>
<section id="leilão-de-permissões-4" class="slide level2">
<h2>Leilão de Permissões</h2>
<ul>
<li>No caso do imposto, o preço unitário da poluição estava sob controle do planejador central.</li>
<li>No caso das permissões, qual variável o planejador controla?
<ul>
<li><strong>A oferta total de permissões</strong> <span class="math inline">\(L\)</span>.</li>
</ul></li>
<li><span class="fragment" data-fragment-index="1">A oferta regula o preço das permissões por meio da condição de Market Clearing:</span></li>
</ul>
<div class="eq-block fragment" data-fragment-index="1">
<p><span class="math display">\[L=E(\sigma )=\sum_{j=1}^{J} {e}_{j}(\sigma )\]</span></p>
</div>
</section>
<section id="preço-e-quantidade-são-o-mesmo-botão" class="slide level2">
<h2>Preço e quantidade são o mesmo botão</h2>
<div class="no-bullet">
<p>Se o governo conhece a demanda agregada por permissões ou a curva de custo de abatimento agregada, pode definir <span class="math inline">\(L\)</span> de modo a induzir <span class="math inline">\({E}^{*}\)</span>.</p>
</div>
<div class="diagram">
<p><img data-src="../_assets/figuras/07-leilao.svg" style="max-height:322px"></p>
</div>
<ul>
<li><span class="fragment" data-fragment-index="1">Com informação perfeita, escolher a altura ou escolher a largura dá na mesma. Nas próximas aulas, entretanto, veremos que isso não é verdade sob Informação Assimétrica.</span></li>
</ul>
</section>
<section id="exercício-quanto-vale-uma-permissão" class="slide level2">
<h2>Exercício: quanto vale uma permissão</h2>
<div class="no-bullet">
<p>Em duplas, 5 minutos. As mesmas usinas: cada uma emite 50 t e corta em blocos de 10 t, aos custos abaixo (em R$ mil), e cada 10 t emitidas causam R$ 45 mil de dano.</p>
</div>
<div class="tabela">
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>1º bloco</th>
<th>2º</th>
<th>3º</th>
<th>4º</th>
<th>5º</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Usina A</td>
<td>10</td>
<td>20</td>
<td>30</td>
<td>40</td>
<td>50</td>
</tr>
<tr class="even">
<td>Usina B</td>
<td>20</td>
<td>40</td>
<td>60</td>
<td>80</td>
<td>100</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li>O governo quer as 40 t eficientes, então emite <span class="math inline">\(L=4\)</span> permissões de 10 t. <strong>Não define preço nenhum.</strong></li>
<li><strong>(a)</strong> Quanto vale para cada usina a 1ª permissão? E a 2ª?</li>
<li><strong>(b)</strong> O governo <strong>leiloa</strong> as 4. Quem leva quantas, e onde o preço para?</li>
<li><strong>(c)</strong> Se, em vez de leiloar, ele <strong>entregar 2 para cada uma</strong>, o que muda?</li>
</ul>
</section>
<section id="as-ofertas-e-o-preço-que-sai-delas" class="slide level2">
<h2>As ofertas, e o preço que sai delas</h2>
<div class="no-bullet">
<p><strong>(a)</strong> Uma permissão dispensa o bloco mais caro que a usina teria de cortar. Com <span class="math inline">\(k\)</span> permissões ela emite <span class="math inline">\(10k\)</span> e corta os <span class="math inline">\(5-k\)</span> blocos mais baratos.</p>
</div>
<div class="tabela">
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>1ª permissão</th>
<th>2ª</th>
<th>3ª</th>
<th>4ª</th>
<th>5ª</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Usina A</td>
<td>50</td>
<td>40</td>
<td>30</td>
<td>20</td>
<td>10</td>
</tr>
<tr class="even">
<td>Usina B</td>
<td>100</td>
<td>80</td>
<td>60</td>
<td>40</td>
<td>20</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><span class="fragment" data-fragment-index="1"><strong>(b)</strong> As quatro maiores ofertas são 100, 80 e 60, de B, e 50, de A. <strong>B leva 3 e A leva 1</strong>.</span></li>
<li><span class="fragment" data-fragment-index="1">O preço é definido pelo leilão: fica entre maior oferta perdedora (40) e menor oferta vencedora (50).</span></li>
</ul>
</section>
<section id="o-regulador-escolhe-quantidade-e-induz-preço" class="slide level2">
<h2>O regulador escolhe quantidade e induz preço</h2>
<div class="diagram">
<p><img data-src="../_assets/figuras/07-exercicio-leilao.svg" style="max-height:326px"></p>
</div>
<ul>
<li>O dano marginal de 45 informa ao governo <strong>quantas</strong> permissões emitir (não o preço, como no caso do imposto).</li>
<li>Com blocos discretos há um degrau em <span class="math inline">\(L=4\)</span>: vários preços de equilíbrio ao invés de um único ponto.</li>
</ul>
</section>
<section id="mesmas-permissões-contas-diferentes" class="slide level2">
<h2>Mesmas permissões, contas diferentes</h2>
<div class="no-bullet">
<p><strong>(c)</strong> Com 2 permissões cada, A vende uma a B: ela vale 40 para A e 60 para B. As duas terminam com 1 e 3, como no leilão.</p>
</div>
<div class="cmp">
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Permissões de A</th>
<th>de B</th>
<th>Abatimento</th>
<th>Conta de A</th>
<th>Conta de B</th>
<th>Ao governo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Leilão das 4</td>
<td>1</td>
<td>3</td>
<td>160</td>
<td>145</td>
<td>195</td>
<td>180</td>
</tr>
<tr class="even">
<td>Entrega de 2 e 2, com troca</td>
<td>1</td>
<td>3</td>
<td>160</td>
<td>55</td>
<td>105</td>
<td>0</td>
</tr>
<tr class="odd">
<td><strong>Diferença</strong></td>
<td>0</td>
<td>0</td>
<td><strong>0</strong></td>
<td><strong>90</strong></td>
<td><strong>90</strong></td>
<td><strong>180</strong></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li>A conta toma <span class="math inline">\(\sigma =45\)</span>. As 2 permissões grátis valem <span class="math inline">\(2\sigma\)</span> para cada usina, e é essa a diferença.</li>
<li><span class="fragment" data-fragment-index="1">O abatimento é 160 nas duas rotas, contra 180 do padrão uniforme: a troca recupera os 20 da aula passada.</span></li>
<li><span class="fragment" data-fragment-index="2"><strong>Repartir as permissões muda quem paga, e não quanto se polui.</strong></span></li>
</ul>
</section>
<section id="distribuição-de-permissões-transferíveis" class="slide level2 section-cover">
<h2>Distribuição de Permissões Transferíveis</h2>
</section>
<section id="distribuição-de-permissões-transferíveis-1" class="slide level2">
<h2>Distribuição de Permissões Transferíveis</h2>
<div class="no-bullet">
<p>Ao invés de leiloar permissões diretamente, o governo pode distribuir uma dotação inicial de permissões para cada firma.</p>
</div>
<ul>
<li>Isto significa que firma pode poluir sem custo até determinado nível, que é definido pela dotação inicial de permissões.</li>
<li>Note que a forma como o governo escolhe essa dotação tem implicações distributivas.</li>
</ul>
</section>
<section id="distribuição-de-permissões-transferíveis-2" class="slide level2">
<h2>Distribuição de Permissões Transferíveis</h2>
<div class="no-bullet">
<p>Firmas podem comprar e vender permissões</p>
</div>
<ul>
<li>Uma firma pode aumentar seu limite de poluição comprando permissões de outra firma.</li>
<li>Temos, portanto, uma estrutura de <strong>mercado competitivo de permissões</strong>.</li>
</ul>
<div class="no-bullet">
<p>Isto é similar ao que vimos na seção de Comando e Controle com Cotas Negociáveis.</p>
</div>
</section>
<section id="distribuição-de-permissões-transferíveis-3" class="slide level2">
<h2>Distribuição de Permissões Transferíveis</h2>
<div class="no-bullet">
<p>Suponha que a firma <span class="math inline">\(j\)</span> receba permissões equivalentes a <span class="math inline">\(\bar{e}_{j}\)</span>.</p>
</div>
<ul>
<li>É como se fosse transferência lump sum do governo para a firma.</li>
</ul>
<div class="no-bullet">
<p>Denote <span class="math inline">\(\sigma\)</span> como o preço de cada permissão no mercado. O custo total da firma é dado por</p>
</div>
<div class="eq-block">
<p><span class="math display">\[T{C}_{j}\left({e}_{j}\right)={C}_{j}\left({e}_{j}\right)+\sigma \left({e}_{j}-\bar{e}_{j}\right)\]</span></p>
</div>
<div class="no-bullet">
<p>Note que</p>
</div>
<ul>
<li><span class="math inline">\({e}_{j}-\bar{e}_{j}&gt;0\)</span> <strong>significa que a firma compra</strong> permissões adicionais.</li>
<li><span class="math inline">\({e}_{j}-\bar{e}_{j}&lt;0\)</span> <strong>significa que a firma vende</strong> permissões que estão sobrando.</li>
</ul>
</section>
<section id="distribuição-de-permissões-transferíveis-4" class="slide level2">
<h2>Distribuição de Permissões Transferíveis</h2>
<div class="no-bullet">
<p>Minimização de custos implica novamente em <span class="math inline">\(-{C}_{j}^{′}\left({e}_{j}\right)=\sigma\)</span></p>
</div>
<ul>
<li>Firmas reduzem poluição até que o custo marginal de abatimento seja igual ao preço da permissão.</li>
<li>Note que a dotação <span class="math inline">\(\bar{e}_{j}\)</span> <strong>não aparece</strong> na condição de primeira ordem, pois é exógena.</li>
</ul>
<div class="no-bullet">
<p>Qual é a condição de equilíbrio de mercado neste caso?</p>
</div>
<div class="eq-block">
<p><span class="math display">\[\sum_{j=1}^{J} {e}_{j}\left(\sigma \right)=\sum_{j=1}^{J} \bar{e}_{j}=L\]</span></p>
</div>
<div class="no-bullet">
<p><span class="fragment" data-fragment-index="1">O preço <span class="math inline">\(\sigma\)</span> é determinado implicitamente por essa condição.</span></p>
</div>
</section>
<section id="quem-compra-e-quem-vende" class="slide level2">
<h2>Quem compra e quem vende</h2>
<div class="no-bullet">
<p>Voltemos ao caso de apenas duas firmas, com a dotação <span class="math inline">\(\bar{e}\)</span> repartida igualmente.</p>
</div>
<div class="diagram">
<p><img data-src="../_assets/figuras/07-permissoes-1.svg" style="max-height:300px"></p>
</div>
<ul>
<li>A Firma 1 abate caro, então prefere comprar. A Firma 2 abate barato, então prefere vender e abater mais.</li>
</ul>
</section>
<section id="as-áreas" class="slide level2">
<h2>As áreas</h2>
<ul>
<li>Firma 1 gasta <span class="math inline">\(A\)</span> em custo de abatimento e paga <span class="math inline">\(B\)</span> para comprar <span class="math inline">\({e}_{1}\left(\sigma \right)-\bar{e}\)</span> permissões.</li>
<li>Firma 2 gasta <span class="math inline">\(D+E\)</span> em abatimento, mas ganha <span class="math inline">\(E+F\)</span> vendendo <span class="math inline">\(\bar{e}-{e}_{2}\left(\sigma \right)\)</span> permissões.</li>
</ul>
<div class="diagram">
<p><img data-src="../_assets/figuras/07-permissoes-2.svg" style="max-height:290px"></p>
</div>
</section>
<section id="as-áreas-1" class="slide level2">
<h2>As áreas</h2>
<div class="no-bullet">
<p>Gasto da indústria com abatimento é <span class="math inline">\(\left(A+D+E\right)\)</span> ao invés de <span class="math inline">\(\left(A+B+C+D\right)\)</span>.</p>
</div>
<ul>
<li>Sabendo que <span class="math inline">\(B=E+F\)</span>, temos poupança de <span class="math inline">\(\left(A+E+F+C+D\right)-\left(A+D+E\right)=C+F\)</span>.</li>
</ul>
<div class="diagram">
<p><img data-src="../_assets/figuras/07-permissoes-3.svg" style="max-height:290px"></p>
</div>
</section>
<section id="independência-dos-instrumentos" class="slide level2">
<h2>Independência dos instrumentos</h2>
<div class="no-bullet">
<p>Vimos que a mesma alocação surge no casos em que leilão ou mercado de permissões induzem preço <span class="math inline">\(\sigma\)</span>.</p>
</div>
<ul>
<li>A dotação <span class="math inline">\(\bar{e}_{j}\)</span> entra no custo total como parcela <strong>fixa</strong>, então sai na derivada.</li>
<li><span class="fragment" data-fragment-index="1">O que a firma decide depende de <span class="math inline">\(\sigma\)</span>, e <span class="math inline">\(\sigma\)</span> depende de <span class="math inline">\(L\)</span>, não de como <span class="math inline">\(L\)</span> foi repartido.</span></li>
<li><span class="fragment" data-fragment-index="2">Remete ao Teorema de Coase: direitos de propriedade bem definidos e negociáveis levam ao mesmo lugar, independentemente de quem os recebe <span class="citation" data-cites="montgomery1972">(<a href="#/referências" role="doc-biblioref" onclick="">Montgomery 1972</a>)</span>.</span></li>
<li><span class="fragment" data-fragment-index="3">A ressalva também é a mesma: se houver custo de transação, a dotação inicial passa a importar.</span></li>
</ul>
</section>
<section id="exemplo-prático" class="slide level2">
<h2>Exemplo Prático</h2>
<div class="no-bullet">
<p>O mercado europeu de carbono (EU ETS) permite testar isso com dados <span class="citation" data-cites="zaklan2023">(<a href="#/referências" role="doc-biblioref" onclick="">Zaklan 2023</a>)</span>.</p>
</div>
<ul>
<li>Em 2013, geradores de energia da maior parte dos países perderam a alocação gratuita e passaram a comprar permissões em leilão.</li>
<li>Oito países mantiveram alocação gratuita por uma regra de exceção.</li>
<li>Diff-in-Diff comparando quem perdeu a alocação gratuita versus quem manteve, com dados de 2009 a 2017.</li>
</ul>
</section>
<section id="exemplo-prático-1" class="slide level2">
<h2>Exemplo Prático</h2>
<ul>
<li>Para o setor como um todo, e para os grandes emissores, <strong>a independência não é rejeitada</strong>: perder a alocação gratuita não muda a emissão.
<ul>
<li>Quem perdeu a dotação respondeu <strong>comprando mais permissões</strong>, e não poluindo menos.</li>
</ul></li>
<li><span class="fragment" data-fragment-index="1">Para os pequenos emissores, a emissão cai cerca de 20%, o que sugere custo de transação ou limitação organizacional.</span></li>
<li><span class="fragment" data-fragment-index="2">Como eles respondem por parcela pequena da emissão, a independência sobrevive no agregado.</span></li>
</ul>
</section>
<section id="subsídios" class="slide level2 section-cover">
<h2>Subsídios</h2>
</section>
<section id="voltando-aos-instrumentos-de-preço" class="slide level2">
<h2>Voltando aos instrumentos de preço</h2>
<div class="step-map">
<div class="step">
<p><strong>1. Prescrever</strong> o regulador diz o que fazer: tecnologia obrigatória ou limite de emissão por fonte</p>
</div>
<div class="step now">
<p><strong>2. Precificar</strong> o regulador põe um preço na emissão: imposto ou subsídio</p>
</div>
<div class="step">
<p><strong>3. Limitar quantidade</strong> o regulador fixa o total e deixa o mercado repartir permissões</p>
</div>
<div class="step">
<p><strong>4. Informar</strong> o regulador informa população com inventários de emissão, selos e certificações</p>
</div>
</div>
<ul>
<li>Na aula passada, tratamos de imposto.</li>
<li>Entretanto, cobrar R$ 10 por tonelada emitida ou pagar R$ 10 por tonelada abatida dão o mesmo incentivo <strong>na margem</strong> <span class="citation" data-cites="keohane2016">(<a href="#/referências" role="doc-biblioref" onclick="">Keohane e Olmstead 2016</a>)</span>. Vejamos.</li>
</ul>
</section>
<section id="subsídios-1" class="slide level2">
<h2>Subsídios</h2>
<div class="no-bullet">
<p>Às vezes, é mais factível subsidiar firmas para que adotem tecnologias limpas ao invés de tributar a poluição.</p>
</div>
<ul>
<li>Neste caso, a alocação de direitos de propriedade é diferente.</li>
<li><strong>A sociedade paga às firmas</strong> para que reduzam poluição.</li>
</ul>
<div class="no-bullet">
<p>É a pergunta distributiva do Teorema de Coase, de novo: o direito de poluir é da firma e consumidores precisam incentivá-la a reduzir poluição.</p>
</div>
</section>
<section id="subsídios-2" class="slide level2">
<h2>Subsídios</h2>
<div class="no-bullet">
<p>Suponha que uma firma receba subsídio para reduzir poluição abaixo de algum nível de referência.</p>
</div>
<ul>
<li>Usaremos a escolha ótima individual da firma como esse <em>nível de referência</em>. (<span class="math inline">\(\hat{e}_{j}\)</span>)</li>
<li>Vamos definir o subsídio por unidade reduzida de poluição como <span class="math inline">\(\psi\)</span>.</li>
</ul>
<div class="no-bullet">
<p>Assim, a função de custo total da poluição fica</p>
</div>
<div class="eq-block">
<p><span class="math display">\[T{C}_{j}\left({e}_{j}\right)={C}_{j}\left({e}_{j}\right)+\psi \left({e}_{j}-\hat{e}_{j}\right)\]</span></p>
</div>
</section>
<section id="subsídios-3" class="slide level2">
<h2>Subsídios</h2>
<div class="no-bullet">
<p>Chegamos a uma C.P.O. similar: <span class="math inline">\(-{C}_{j}^{′}\left({e}_{j}\right)=\psi\)</span></p>
</div>
<ul>
<li>Firma 1 recebe o retângulo da esquerda e Firma 2, o da direita.</li>
</ul>
<div class="diagram">
<p><img data-src="../_assets/figuras/07-subsidio-1.svg" style="max-height:290px"></p>
</div>
<ul>
<li>Com <span class="math inline">\(\psi ={\tau }^{*}\)</span>, as duas param exatamente onde o imposto as faria parar.</li>
</ul>
</section>
<section id="subsídios-4" class="slide level2">
<h2>Subsídios</h2>
<div class="no-bullet">
<p>Subsídios têm uma nuance importante.</p>
</div>
<ul>
<li>A definição do <strong>nível de referência</strong> pode afetar a decisão das firmas em participar ou não do programa de subsídio.</li>
<li>No exemplo anterior, tomamos <span class="math inline">\(\hat{e}_{j}\)</span> como nível de referência. Qual é o problema aqui?
<ul>
<li>Muitas vezes, não saberemos <span class="math inline">\(\hat{e}_{j}\)</span> e precisaremos definir um nível comum para todas as firmas.</li>
</ul></li>
</ul>
</section>
<section id="subsídios-5" class="slide level2">
<h2>Subsídios</h2>
<div class="no-bullet">
<p>Suponha que a referência seja <span class="math inline">\(\bar{e}\)</span>, igual para todas as firmas.</p>
</div>
<ul>
<li>O que a Firma 1 faz?</li>
<li>E a Firma 2?</li>
</ul>
<div class="diagram">
<p><img data-src="../_assets/figuras/07-subsidio-2.svg" style="max-height:290px"></p>
</div>
</section>
<section id="subsídios-6" class="slide level2">
<h2>Subsídios</h2>
<ul>
<li>Firma 1 sai do programa de subsídio.
<ul>
<li>Para receber alguma coisa, teria que abater até <span class="math inline">\(\bar{e}\)</span>, e isso lhe custa mais do que o subsídio paga.</li>
</ul></li>
<li>Firma 2 fica, e recebe <span class="math inline">\(\psi \left(\bar{e}-{e}_{2}^{*}\right)\)</span>.</li>
<li><span class="fragment" data-fragment-index="1">Resultado: a emissão total sobe de 125 para 150, e a alocação deixa de ser eficiente.</span></li>
<li><span class="fragment" data-fragment-index="2">O imposto não tem esse problema, porque o ponto de partida é sempre zero.</span></li>
</ul>
</section>
<section id="mesmo-nível-ótimo-porém-caixa-da-firma-muda" class="slide level2">
<h2>Mesmo nível ótimo, porém caixa da firma muda</h2>
<div class="no-bullet">
<p>Com a referência individual, imposto e subsídio produzem a <strong>mesma</strong> emissão. Mas o caixa da firma vai para lados opostos.</p>
</div>
<div class="cmp">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Imposto <span class="math inline">\({\tau }^{*}=25\)</span></th>
<th>Subsídio <span class="math inline">\(\psi =25\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Emissão da Firma 1</td>
<td>75</td>
<td>75</td>
</tr>
<tr class="even">
<td>Custo de abatimento</td>
<td>312,5</td>
<td>312,5</td>
</tr>
<tr class="odd">
<td>Fluxo de dinheiro</td>
<td>paga 1.875</td>
<td>recebe 625</td>
</tr>
<tr class="even">
<td><strong>Resultado para a firma</strong></td>
<td><strong>2.187,5 de despesa</strong></td>
<td><strong>312,5 de ganho</strong></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li>São 2.500 de diferença para a Firma 1, e o mesmo vale para a Firma 2.</li>
<li><span class="fragment" data-fragment-index="1">No longo prazo, o imposto empurra firmas para fora do setor e o subsídio atrai firmas para dentro.</span></li>
<li><span class="fragment" data-fragment-index="2">Mais firmas no setor significa mais emissão total, mesmo com cada uma emitindo o mesmo.</span></li>
</ul>
</section>
<section id="as-quatro-políticas-lado-a-lado" class="slide level2">
<h2>As quatro políticas lado a lado</h2>
<div class="cmp">
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Imposto <span class="math inline">\({\tau }^{*}\)</span></th>
<th>Leilão de <span class="math inline">\(L\)</span></th>
<th>Permissões grátis</th>
<th>Subsídio <span class="math inline">\(\psi\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Emissão total</td>
<td>125</td>
<td>125</td>
<td>125</td>
<td>125</td>
</tr>
<tr class="even">
<td><span class="math inline">\(CM{g}_{1}\)</span> e <span class="math inline">\(CM{g}_{2}\)</span></td>
<td><span class="math inline">\(25=25\)</span></td>
<td><span class="math inline">\(25=25\)</span></td>
<td><span class="math inline">\(25=25\)</span></td>
<td><span class="math inline">\(25=25\)</span></td>
</tr>
<tr class="odd">
<td>Custo de abatimento</td>
<td>938</td>
<td>938</td>
<td>938</td>
<td>938</td>
</tr>
<tr class="even">
<td>Custo social</td>
<td>2.500</td>
<td>2.500</td>
<td>2.500</td>
<td>2.500</td>
</tr>
<tr class="odd">
<td><strong>Quem paga a quem?</strong></td>
<td><strong>firmas ao governo, 3.125</strong></td>
<td><strong>firmas ao governo, 3.125</strong></td>
<td><strong>firma 1 à firma 2, 312,5</strong></td>
<td><strong>governo às firmas, 1.875</strong></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li>As quatro linhas de cima são idênticas. A de baixo separa uma política da outra em termos <strong>distributivos</strong>.</li>
</ul>
</section>
<section id="concluindo" class="slide level2">
<h2>Concluindo</h2>
<ul>
<li>Distribuir permissões de graça chega ao mesmo <span class="math inline">\({E}^{*}\)</span> do imposto, sem transferência ao governo.</li>
<li>A alocação final <strong>não</strong> depende de quem recebeu as permissões, e sim de quantas foram emitidas.</li>
<li><span class="fragment" data-fragment-index="1">Isso vale enquanto o mercado funcionar. Com custo de transação, a dotação volta a importar, como nos pequenos emissores do EU ETS.</span></li>
<li><span class="fragment" data-fragment-index="2">Fica uma pergunta para a próxima aula: tudo isso supôs que o regulador conhece <span class="math inline">\(D′\)</span> e as curvas de custo. E quando ele não conhece?</span></li>
</ul>
</section>
<section id="referências" class="slide level2 smaller scrollable">
<h2>Referências</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-keohane2016" class="csl-entry" role="listitem">
Keohane, Nathaniel O., e Sheila M. Olmstead. 2016. <em>Markets and the Environment</em>. 2.ª ed. Island Press.
</div>
<div id="ref-montgomery1972" class="csl-entry" role="listitem">
Montgomery, W. David. 1972. <span>«Markets in Licenses and Efficient Pollution Control Programs»</span>. <em>Journal of Economic Theory</em> 5 (3): 395–418. <a href="https://doi.org/10.1016/0022-0531(72)90049-X">https://doi.org/10.1016/0022-0531(72)90049-X</a>.
</div>
<div id="ref-phaneuf2017" class="csl-entry" role="listitem">
Phaneuf, Daniel J., e Till Requate. 2017. <em>A Course in Environmental Economics: Theory, Policy, and Practice</em>. Cambridge University Press.
</div>
<div id="ref-zaklan2023" class="csl-entry" role="listitem">
Zaklan, Aleksandar. 2023. <span>«Coase and Cap-and-Trade: Evidence on the Independence Property from the European Carbon Market»</span>. <em>American Economic Journal: Economic Policy</em> 15 (2): 526–58. <a href="https://doi.org/10.1257/pol.20210028">https://doi.org/10.1257/pol.20210028</a>.
</div>
</div>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>EAE1317 — Economia do Meio Ambiente e dos Recursos Naturais</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 8.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiada");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiada");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/rpucci-usp\.github\.io\/eae1317\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>